version: '3.3'

services:
  db:
    container_name: docker_mysql
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT_DOCKER}"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default
    restart: always
    command: 
      --default-authentication-plugin=mysql_native_password

  api:
    container_name: docker_function
    build:
      context: .
      dockerfile: api.Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app/
    networks:
      - default

networks:
  default:

volumes:
  mysql_data:
