version: '3.3'

services:
  db:
    container_name: docker_mysql
    build:
      context: .
      dockerfile: internal/db.Dockerfile
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT_DOCKER}"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - default
    restart: always
    command: 
      --default-authentication-plugin=mysql_native_password
      --innodb-fast-shutdown=0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    container_name: docker_function
    build:
      context: .
      dockerfile: internal/api.Dockerfile
    ports:
      - "${HOST_PORT}:${HOST_PORT_DOCKER}"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app/
    networks:
      - default

networks:
  default:

volumes:
  mysql_data: